#!/usr/bin/env bash

usage() {
	cat <<-EOF
		Logs commands to a sqlite3 database for later study.

		Usage: $(basename "${0}") [-h|V] | ([-d[=]<DATABASE>] ([-s]) | ([(-l|v [-n[=]<INTEGER>]) | ([-e[=][PATH]]) [-u[=]<USER>]]) | ([-a|r] <COMMAND>))

		Options:
		  -h, --help                Show this help message and exit.
		  -V, --version             Show version information and exit.
		  -s, --setup               Perform database setup and exit.
		  -d, --database <DATABASE> Use the database located at <DATABASE>, creating it if necessary. Defaults to '\$HOME/.cmd-log.db' if unspecified.
		  -e, --export [PATH]       Export logged commands from the database to the specified [PATH] as a csv. Defaults to './cmd-log.csv' if unspecified. Does not replace existing files.
		  -a, --add-filter          Add a filter that prevents logging commands that start with <COMMAND>. (Case sensitive)
		  -r, --remove-filter       Remove an existing filter for <COMMAND>. (Case sensitive)
		  -l, --list-filters        List existing filters and exit.
		  -n, --limit <INTEGER>     Set configuration to limit listed filters or log entries to <INTEGER>. Defaults to 10 on database initialization or if an invalid value is encountered.
		  -v, --view                List the 'n' most recent log entries. 'n' is determined by the '--limit' flag if specified, or by per-user configuration value if unspecified.
		  -u, --user <USER>         List or export logged commands for specified <USER> instead of '\$USER'.
		      --                    Stop processing command line arguments.
	EOF
}

version() {
	cat <<-EOF
		$(basename "${0}") 0.1.0
		Copyright © 2026 Josh Beale <jbeale2023@gmail.com>.
		Licence: The MIT License.
	EOF
}

function setup_user_db() {
	local db
	local srcdir
	local user
	local host
	db="${1}"
	srcdir=$(CDPATH="" cd -- "$(dirname -- "${0}")" && pwd -P)
	if [[ ! -d ${srcdir} ]]; then
		printf "%s: failed to setup user database at path '%s'.\n" "$(basename "${0}")" "${db}" >&2
		return 5
	fi
	user=$(id -un)
	host=$(hostname)
	sqlite3 "${db}" <"${srcdir}/src/setup.sql" &>/dev/null
	if ! chmod 600 "${db}"; then
		printf "%s: failed to setup user database at path '%s'.\n" "$(basename "${0}")" "${db}" >&2
		return 5
	fi
	sqlite3 "${db}" <<-EOF &>/dev/null
		.parameter set :user "'${user}'"
		.parameter set :host "'${host}'"
		INSERT OR IGNORE INTO users (user_name, host_name)
		VALUES (:user, :host);

		INSERT OR IGNORE INTO configuration (key, value)
		VALUES (:user || '.number_entries_displayed', "10");
	EOF
	printf "%s: setup user database at path '%s'.\n" "$(basename "${0}")" "${db}" >&2
}

function log_command() {
	local db
	local user
	local host
	local command
	local timestamp
	db="${1}"
	user=$(id -un)
	host=$(hostname)
	printf -v command -- "%s" "${2}"
	printf -v timestamp "%(%Y-%m-%d %H:%M:%S)T" -1
	if [[ ! -f "${db}" ]]; then
		setup_user_db "${db}" || return "${?}"
	fi
	sqlite3 "${db}" <<-EOF &>/dev/null
		.parameter set :user "'${user}'"
		.parameter set :host "'${host}'"
		.parameter set :timestamp "'${timestamp}'"
		.parameter set :command "'${command}'"
		INSERT INTO command_log (id, user_name, host_name, datetime, command)
		SELECT NULL, :user, :host, :timestamp, :command
		WHERE NOT EXISTS (
			SELECT value
			FROM configuration
			WHERE key = :user || '.ignore_command' AND
			:command LIKE value || '%'
		);
	EOF
}

function add_filter() {
	local db
	local user
	local filter
	db="${1}"
	user=$(id -un)
	filter="${2}"
	if [[ ! -f "${db}" ]]; then
		setup_user_db "${db}" || return "${?}"
	fi
	if ! sqlite3 "${db}" <<-EOF &>/dev/null; then
		.parameter set :user "'${user}'"
		.parameter set :filter "'${filter}'"
		INSERT INTO configuration (key, value)
		VALUES (:user || '.ignore_command', :filter);
	EOF
		printf "%s: failed to add filter '%s'.\n" "$(basename "${0}")" "${filter}" >&2
		return 4
	fi
	printf "%s: successfully added filter '%s'.\n" "$(basename "${0}")" "${filter}" >&2
}

function remove_filter() {
	local db
	local user
	local filter
	local rows
	db="${1}"
	user=$(id -un)
	filter="${2}"
	if [[ ! -f "${db}" ]]; then
		setup_user_db "${db}" || return "${?}"
	fi
	rows=$(
		sqlite3 "${db}" <<-EOF 2>/dev/null
			.parameter set :user "'${user}'"
			.parameter set :filter "'${filter}'"
			DELETE FROM configuration WHERE key = :user || '.ignore_command' AND value = :filter;
			SELECT changes();
		EOF
	)
	if ((rows != 1)); then
		printf "%s: failed to remove filter '%s'.\n" "$(basename "${0}")" "${filter}" >&2
		return 4
	fi
	printf "%s: successfully removed filter '%s'.\n" "$(basename "${0}")" "${filter}" >&2
}

function list_filters() {
	local db
	local user
	local limit
	local rows
	db="${1}"
	user="$(id -un)"
	if [[ ! -f "${db}" ]]; then
		setup_user_db "${db}" || return "${?}"
	fi
	limit=$(read_list_limit "${db}")
	rows=$(
		sqlite3 "${db}" <<-EOF 2>/dev/null
			.parameter set :user "'${user}'"
			SELECT COUNT(value) FROM configuration WHERE key = :user || '.ignore_command';
		EOF
	)
	printf "Displaying %s of %s Current Filters\n" "$((rows > limit ? limit : rows))" "${rows}"
	sqlite3 -column "${db}" 2>/dev/null <<-EOF
		.parameter set :user "'${user}'"
		.parameter set :limit "'${limit}'"
		SELECT value FROM configuration WHERE key = :user || '.ignore_command' LIMIT :limit;
	EOF
}

function configure_list_limit() {
	local db
	local user
	local limit
	db="${1}"
	user=$(id -un)
	limit="${2}"
	if [[ ! -f "${db}" ]]; then
		setup_user_db "${db}" || return "${?}"
	fi
	sqlite3 "${db}" <<-EOF &>/dev/null
		.parameter set :user "'${user}'"
		.parameter set :limit "'${limit}'"
		INSERT INTO configuration (key, value)
		VALUES (:user || '.number_entries_displayed', :limit)
		ON CONFLICT(key) WHERE key LIKE '%.number_entries_displayed'
		DO UPDATE SET value = excluded.value;
	EOF
}

function read_list_limit() {
	local db
	local user
	local limit
	db="${1}"
	user=$(id -un)
	if [[ ! -f "${db}" ]]; then
		setup_user_db "${db}" || return "${?}"
	fi
	limit=$(
		sqlite3 "${db}" <<-EOF
			.parameter set :user "'${user}'"
			SELECT value FROM configuration
			WHERE key = :user || '.number_entries_displayed';
		EOF
	)
	if [[ ! "${limit}" =~ ^[0-9]+$ ]]; then
		limit=10
		configure_list_limit "${db}" "${limit}"
		printf "%s: invalid display limit was found. It was reset to the default value of 10 for user: %s\n" "$(basename "${0}")" "${user}" >&2
	fi
	printf "%s" "${limit}"
}

function view_log_entries() {
	local db
	local user
	local limit
	local rows
	db="${1}"
	user="${2}"
	if [[ ! -f "${db}" ]]; then
		setup_user_db "${db}" || return "${?}"
	fi
	limit=$(read_list_limit "${db}")
	if [[ "${user}" != "$(id -un)" ]] && (("$(id -u)" != 0)); then
		printf "%s: viewing command log for other users requires root priveleges.\n" "$(basename "${0}")" >&2
		return 7
	fi
	rows=$(
		sqlite3 "${db}" <<-EOF 2>/dev/null
			.parameter set :user "'${user}'"
			SELECT COUNT(id) FROM command_log WHERE user_name = :user;
		EOF
	)
	printf "Displaying %s of %s Logged Commands\n" "$((rows > limit ? limit : rows))" "${rows}"
	sqlite3 -column "${db}" 2>/dev/null <<-EOF
		.parameter set :user "'${user}'"
		.parameter set :limit "'${limit}'"
		SELECT * FROM (
			SELECT * 
			FROM command_log
			WHERE user_name = :user
			ORDER BY id DESC
			LIMIT :limit
		)
		ORDER BY id ASC;
	EOF
}

function export_to_csv() {
	local db
	local export_path
	local user
	db="${1}"
	export_path="${2}"
	user="${3}"
	if [[ ! -f "${db}" ]]; then
		setup_user_db "${db}" || return "${?}"
	fi
	if [[ -e ${export_path} ]]; then
		printf "%s: file exists at path '%s'.\n" "$(basename "${0}")" "${export_path}" >&2
		return 6
	fi
	if [[ -z "${user}" ]]; then
		if (("$(id -u)" != 0)); then
			printf "%s: exporting command log for all users requires root priveleges.\n" "$(basename "${0}")" >&2
			return 7
		fi
		sqlite3 "${db}" <<-EOF >"${export_path}" 2>/dev/null
			.header on
			.mode csv
			SELECT * FROM command_log;
		EOF
		chown "${SUDO_USER}":"${SUDO_USER}" "${export_path}"
		printf "%s: exported logged commands for all users to path '%s'.\n" "$(basename "${0}")" "${export_path}" >&2
		return 0
	fi
	if [[ "${user}" != "$(id -un)" ]] && (("$(id -u)" != 0)); then
		printf "%s: exporting command log for other users requires root priveleges.\n" "$(basename "${0}")" >&2
		return 7
	fi
	sqlite3 "${db}" <<-EOF >"${export_path}" 2>/dev/null
		.parameter set :user "'${user}'"
		.header on
		.mode csv
		SELECT * FROM command_log
		WHERE user_name = :user;
	EOF
	printf "%s: exported logged commands for user: '%s' to path '%s'.\n" "$(basename "${0}")" "${user}" "${export_path}" >&2
}

function main() {
	if ! sqlite3 --version &>/dev/null; then
		printf "%s: sqlite3 is required. Please install it and try again.\n" "$(basename "${0}")" >&2
		return 3
	fi
	local db
	local command
	local limit
	local _old_limit
	local adding_filter
	local removing_filter
	local listing_filters
	local listing_logged_commands
	local view_user
	local export_mode
	local export_path
	local do_setup
	while [[ "${#}" -gt 0 ]]; do
		if [[ "${1}" =~ ^(-h)|(--h(e(l(p)?)?)?) ]]; then
			usage
			shift 1
			return 0
		elif [[ "${1}" =~ ^(-V)|(--v(e(r(s(i(o(n)?)?)?)?)?)?) ]]; then
			version
			shift 1
			return 0
		elif [[ "${1}" =~ ^(-s)|(--s(e(t(u(p)?)?)?)?) ]]; then
			do_setup=true
			shift 1
		elif [[ "${1}" =~ ^(-l)|(--l(i(s(t(-(f(i(l(t(e(r(s)?)?)?)?)?)?)?)?)?)?)?) ]]; then
			listing_filters=true
			shift 1
		elif [[ "${1}" =~ ^(-a)|(--a(d(d(-(f(i(l(t(e(r)?)?)?)?)?)?)?)?)?) ]]; then
			adding_filter=true
			shift 1
		elif [[ "${1}" =~ ^(-r)|(--r(e(m(o(v(e(f(i(l(t(e(r)?)?)?)?)?)?)?)?)?)?)?) ]]; then
			removing_filter=true
			shift 1
		elif [[ "${1}" =~ ^(-v)|(--v(i(e(w)?)?)?) ]]; then
			listing_logged_commands=true
			shift 1
		elif [[ "${1}" =~ ^(-d)|(--d(a(t(a(b(a(s(e)?)?)?)?)?)?)?) ]]; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				db="${1#"${leader}"}"
				;;
			--database*)
				db="${1#--database}"
				;;
			--databas*)
				db="${1#--databas}"
				;;
			--databa*)
				db="${1#--databa}"
				;;
			--datab*)
				db="${1#--datab}"
				;;
			--data*)
				db="${1#--data}"
				;;
			--dat*)
				db="${1#--dat}"
				;;
			--da*)
				db="${1#--da}"
				;;
			--d*)
				db="${1#--d}"
				;;
			-d*)
				db="${1#-d}"
				;;
			*)
				printf "%s: invalid database format -- '%s\n'" "$(basename "${0}")" "${1}" >&2
				return 2
				;;
			esac
			if [[ -z "${db}" ]]; then
				if [[ -n "${2}" ]]; then
					case "${2}" in
					-*)
						printf "%s: If '--database' is specified, a database path must be provided.\n" "$(basename "${0}")" >&2
						return 2
						;;
					*)
						db="${2}"
						shift 1
						;;
					esac
				else
					printf "%s: If '--database' is specified, a database path must be provided.\n" "$(basename "${0}")" >&2
					return 2
				fi
			fi
			shift 1
		elif [[ "${1}" =~ ^(-n)|(--l(i(m(i(t)?)?)?)?) ]]; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				limit="${1#"${leader}"}"
				;;
			--limit*)
				limit="${1#--limit}"
				;;
			--limi*)
				limit="${1#--limi}"
				;;
			--lim*)
				limit="${1#--lim}"
				;;
			--li*)
				limit="${1#--li}"
				;;
			--l*)
				limit="${1#--l}"
				;;
			-n*)
				limit="${1#-n}"
				;;
			*)
				printf "%s: invalid limit format -- '%s\n'" "$(basename "${0}")" "${1}" >&2
				return 2
				;;
			esac
			if [[ -z "${limit}" ]]; then
				if [[ -n "${2}" ]]; then
					case "${2}" in
					-*)
						printf "%s: If '--limit' is specified, a limit must be provided.\n" "$(basename "${0}")" >&2
						return 2
						;;
					*)
						limit="${2}"
						shift 1
						;;
					esac
				else
					printf "%s: If '--limit' is specified, a limit must be provided.\n" "$(basename "${0}")" >&2
					return 2
				fi
			fi
			if [[ ! "${limit}" =~ ^[0-9]+$ ]]; then
				printf "%s: invalid limit format -- '%s\n'" "$(basename "${0}")" "${limit}" >&2
				return 2
			fi
			shift 1
		elif [[ "${1}" =~ ^(-u)|(--u(s(e(r)?)?)?) ]]; then
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				view_user="${1#"${leader}"}"
				;;
			--user*)
				view_user="${1#--user}"
				;;
			--use*)
				limit="${1#--use}"
				;;
			--us*)
				limit="${1#--us}"
				;;
			--u*)
				limit="${1#--u}"
				;;
			-u*)
				limit="${1#-u}"
				;;
			*)
				printf "%s: invalid user format -- '%s\n'" "$(basename "${0}")" "${1}" >&2
				return 2
				;;
			esac
			if [[ -z "${view_user}" ]]; then
				if [[ -n "${2}" ]]; then
					case "${2}" in
					-*)
						printf "%s: If '--user' is specified, a user must be provided.\n" "$(basename "${0}")" >&2
						return 2
						;;
					*)
						view_user="${2}"
						shift 1
						;;
					esac
				else
					printf "%s: If '--user' is specified, a user must be provided.\n" "$(basename "${0}")" >&2
					return 2
				fi
			fi
			shift 1
		elif [[ "${1}" =~ ^(-e)|(--e(x(p(o(r(t)?)?)?)?)?) ]]; then
			export_mode=true
			case "${1}" in
			*=*)
				leader="${1%%=*}="
				export_path="${1#"${leader}"}"
				;;
			--export*)
				export_path="${1#--export}"
				;;
			--expor*)
				export_path="${1#--expor}"
				;;
			--expo*)
				export_path="${1#--expo}"
				;;
			--exp*)
				export_path="${1#--exp}"
				;;
			--ex*)
				export_path="${1#--ex}"
				;;
			--e*)
				export_path="${1#--e}"
				;;
			-e*)
				export_path="${1#-e}"
				;;
			*)
				printf "%s: invalid export format -- '%s\n'" "$(basename "${0}")" "${1}" >&2
				return 2
				;;
			esac
			if [[ -z "${export_path}" ]]; then
				if [[ -n "${2}" ]]; then
					case "${2}" in
					-*) ;;
					*)
						export_path="${2}"
						shift 1
						;;
					esac
				fi
			fi
			shift 1
		elif [[ "${1}" == "--" ]]; then
			shift
			break
		elif [[ "${1}" =~ ^-.* ]]; then
			cat <<-EOF >&2
				$(basename "$0"): invalid option -- '${1}'
				Try '$(basename "${0}") --help' for more information.
			EOF
			return 2
		else
			command="${*}"
			break
		fi
	done
	command="${*}"
	db="${db:-"${HOME}/.cmd-log.db"}"
	adding_filter="${adding_filter:-false}"
	removing_filter="${removing_filter:-false}"
	listing_filters="${listing_filters:-false}"
	listing_logged_commands="${listing_logged_commands:-false}"
	export_mode="${export_mode:-false}"
	do_setup="${do_setup:-false}"
	if "${do_setup}"; then
		if [[ ! -f "${db}" ]]; then
			setup_user_db "${db}" || return "${?}"
		fi
		local srcdir
		srcdir=$(CDPATH="" cd -- "$(dirname -- "${0}")" && pwd -P)
		cat <<-EOF >&2
			Please add the following to the end of your .bashrc to begin logging commands:
			'trap ${srcdir}/$(basename "${0}") --database /path/to/your/database -- "\${BASH_COMMAND}"' DEBUG
			Afterwards, add any desired filters with $(basename "${0}") --add-filter <COMMAND>
		EOF
		return 0
	fi
	_old_limit=$(read_list_limit "${db}")
	limit="${limit:-"${_old_limit}"}"
	if (("${limit}" != "${_old_limit}")); then
		configure_list_limit "${db}" "${limit}"
	fi
	if "${export_mode}"; then
		export_path="$(realpath "${export_path:-"./cmd-log.csv"}")"
		export_to_csv "${db}" "${export_path}" "${view_user}"
		return "${?}"
	else
		view_user="${view_user:-$(id -un)}"
	fi
	if "${listing_filters}" && "${listing_logged_commands}"; then
		printf "%s: If '--list-filters' is specified '--view' can't be specified.\n" "$(basename "${0}")" >&2
		return 2
	elif "${listing_filters}"; then
		list_filters "${db}"
		return 0
	elif "${listing_logged_commands}"; then
		view_log_entries "${db}" "${view_user}"
		return 0
	elif "${adding_filter}" && "${removing_filter}"; then
		printf "%s: If '--add-filter' is specified '--remove-filter' can't be specified.\n" "$(basename "${0}")" >&2
		return 2
	else
		if [[ -z "${command}" ]]; then
			usage
			return 1
		fi
	fi
	if "${adding_filter}"; then
		add_filter "${db}" "${command}" || return "${?}"
	elif "${removing_filter}"; then
		remove_filter "${db}" "${command}" || return "${?}"
	else
		log_command "${db}" "${command}" || return "${?}"
	fi
}

main "${@}" || exit "${?}"
