#!/usr/bin/env bash

if ! sqlite3 --version &>/dev/null; then
	exit 1
fi
if ! uuidgen --version &>/dev/null; then
	exit 1
fi

function setup_user_db() {
	local db
	db="${1:-"${HOME}/.cmd-log.db"}"
	sqlite3 "${db}" < "./src/setup.sql"
	sqlite3 "${db}" <<-EOF
	INSERT OR IGNORE INTO users (user_name, host_name)
	VALUES ("${USER}", "${HOSTNAME}");
	EOF
}

function log_command() {
	local db
	local command
	local timestamp
	local id
	db="${1-"${HOME}/.cmd-log.db"}"
	printf -v command -- "%s" "${2}"
	printf -v timestamp "%(%Y-%m-%d %H:%M:%S)T" -1
	id=$(uuidgen)
	[[ -f "${db}" ]] || setup_user_db "${db}"
	sqlite3 "${db}" <<-EOF
	INSERT INTO command_log (id, user_name, host_name, datetime, command)
	SELECT "${id}", "${USER}", "${HOSTNAME}", "${timestamp}", "${command}"
	WHERE "${command}" NOT LIKE (SELECT ignore_commands FROM configuration) || '%';
	EOF
}
